# Generated by Django 4.1.5 on 2023-04-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название города')),
                ('code', models.CharField(max_length=100, verbose_name='Код города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GetCourseExportID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=40, unique=True, verbose_name='Export_id')),
                ('export_time', models.DateTimeField(auto_now=True, verbose_name='Время экспорта')),
            ],
            options={
                'verbose_name': 'Айдишник',
                'verbose_name_plural': 'Айдишники',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Насзвание поста')),
                ('tg_link', models.CharField(max_length=100, verbose_name='Ссылка на тг')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lection_name', models.CharField(max_length=100, verbose_name='Название лекции')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='URL')),
                ('youtube_url', models.CharField(max_length=100, verbose_name='Cсылка на лекцию')),
                ('pre_photo', models.ImageField(null=True, upload_to='photos/', verbose_name='Превью к лекции')),
                ('lector_inst', models.CharField(max_length=100, null=True, verbose_name='Ссылка на инст лектора')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['lection_name'],
            },
        ),
        migrations.CreateModel(
            name='Speciallity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='URL')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
                ('inst_url', models.CharField(max_length=100, verbose_name='Аккаунт инстаграм')),
                ('vk_url', models.CharField(max_length=100, verbose_name='Аккаунт VK')),
                ('dzen_url', models.CharField(max_length=100, verbose_name='Аккаунт Яндекс.Дзен')),
                ('tg_url', models.CharField(max_length=100, verbose_name='Аккаунт TG')),
                ('medical_directions', models.CharField(max_length=100, verbose_name='Направление медицины')),
                ('additional_speciallity', models.CharField(max_length=100, verbose_name='Доп специальность')),
                ('main_blog_theme', models.CharField(max_length=100, verbose_name='Тематика блога')),
                ('status_club', models.BooleanField(null=True, verbose_name='Подписка на клуб')),
                ('avatar', models.ImageField(default='user_photos/zag.png', null=True, upload_to='user_photos/', verbose_name='Личное фото')),
                ('prodoctorov', models.CharField(max_length=255, null=True, unique=True, verbose_name='ПРОДОКТОРОВ')),
                ('subscribers_inst', models.CharField(max_length=255, null=True, verbose_name='Подписчики инста')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='docstar_site.city')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
            },
        ),
    ]
