# Generated by Django 4.1.5 on 2024-12-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт YOUTUBE'),
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код города'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='additional_speciallity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доп специальность'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docstar_site.city'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dzen_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт Яндекс.Дзен'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='inst_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт инстаграм'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='main_blog_theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тематика блога'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_directions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление медицины'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prodoctorov',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ПРОДОКТОРОВ'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='subscribers_inst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подписчики инста'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tg_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт TG'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='vk_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт VK'),
        ),
    ]
