# Generated by Django 4.1.5 on 2025-01-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0003_alter_doctor_options_remove_doctor_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='members',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать доктора'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='additional_speciallity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп специальность'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docstar_site.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='main_blog_theme',
            field=models.TextField(blank=True, null=True, verbose_name='Тематика блога'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_directions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление медицины'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciallity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='docstar_site.speciallity', verbose_name='Специальность'),
        ),
    ]
