# Generated by Django 4.1.5 on 2025-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0004_remove_doctor_members_doctor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
