# Generated by Django 4.1.5 on 2025-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0005_doctor_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prodoctorov',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ПРОДОКТОРОВ'),
        ),
    ]
