# Generated by Django 4.1.5 on 2025-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0006_doctor_age_doctor_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tg_channel_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Канал TG'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккаунт TikTok'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prodoctorov',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка для записи'),
        ),
    ]
