# Generated by Django 4.1.5 on 2025-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0007_doctor_tg_channel_url_doctor_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='s3_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
