# Generated by Django 4.1.5 on 2025-06-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0010_doctor_additional_cities_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Lection',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='status_club',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cooperation_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Неизвестно'), (1, 'Клуб 6+ месяцев'), (2, 'Бартер по рекламе'), (3, 'Платно навсегда'), (4, 'Подписка'), (5, 'Помилование от READYDOC')], default=0, null=True, verbose_name='Тип размещения'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='additional_cities',
            field=models.ManyToManyField(blank=True, related_name='doctors_additional', to='docstar_site.city', verbose_name='Дополнительные города'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors_primary', to='docstar_site.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='main_blog_theme',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Тематика блога'),
        ),
    ]
