# Generated by Django 4.1.5 on 2025-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0011_delete_knowledge_delete_lection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='marketing_preferences',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='У врачей каких специальностей вы бы хотели приобрести рекламу / договориться о коллаборации?'),
        ),
    ]
