# Generated by Django 4.1.5 on 2025-09-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstar_site', '0012_doctor_marketing_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancersCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город фрилансера',
                'verbose_name_plural': 'Города фрилансеров',
                'db_table': 'freelancers_city',
            },
        ),
        migrations.CreateModel(
            name='FreelancersSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность фрилансера',
                'verbose_name_plural': 'Специальности фрилансеров',
                'db_table': 'freelancers_speciality',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название соцсети')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'db_table': 'social_networks',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город врача', 'verbose_name_plural': 'Города врачей'},
        ),
        migrations.AlterModelOptions(
            name='speciallity',
            options={'ordering': ['name'], 'verbose_name': 'Специальность врача', 'verbose_name_plural': 'Специальности врачей'},
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email фрилансера')),
                ('slug', models.TextField(verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('is_worked_with_doctors', models.BooleanField(default=False, verbose_name='Опыт работы с врачами')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username')),
                ('portfolio_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на портфолио')),
                ('price_category', models.IntegerField(blank=True, null=True, verbose_name='Ценовая категория')),
                ('s3_image', models.TextField(blank=True, null=True, verbose_name='Фотография')),
                ('avatar', models.ImageField(blank=True, default='user_photos/zag.png', null=True, upload_to='user_photos/', verbose_name='Личное фото')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_freelancers', to='docstar_site.freelancerscity', verbose_name='Основной город')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_freelancers', to='docstar_site.freelancersspeciality', verbose_name='Основная специальность')),
            ],
            options={
                'verbose_name': 'Фрилансер',
                'verbose_name_plural': 'Фрилансеры',
                'db_table': 'freelancer',
                'unique_together': {('email', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FreelancersPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancer', verbose_name='Фрилансер')),
            ],
            options={
                'verbose_name': 'Прайс-лист фрилансера',
                'verbose_name_plural': 'Прайс-листы фрилансеров',
                'db_table': 'freelancers_price_list',
                'unique_together': {('freelancer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FreelancerSpecialityM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancer')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancersspeciality')),
            ],
            options={
                'verbose_name': 'Специальность фрилансера (M2M)',
                'verbose_name_plural': 'Специальности фрилансеров (M2M)',
                'db_table': 'freelancer_speciality_m2m',
                'unique_together': {('speciality', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='FreelancerSocialNetworksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancer')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.socialnetworks')),
            ],
            options={
                'verbose_name': 'Соцсеть фрилансера (M2M)',
                'verbose_name_plural': 'Соцсети фрилансеров (M2M)',
                'db_table': 'freelancer_social_networks_m2m',
                'unique_together': {('social_network', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='FreelancerCityM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancerscity')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docstar_site.freelancer')),
            ],
            options={
                'verbose_name': 'Город фрилансера (M2M)',
                'verbose_name_plural': 'Города фрилансеров (M2M)',
                'db_table': 'freelancer_city_m2m',
                'unique_together': {('city', 'freelancer')},
            },
        ),
    ]
