version: '3'

services:
  web:
    build: .
    environment:
      DB_NAME: sql
      DB_USER: maxim
      DB_PASSWORD: re-play
      DB_HOST: postgresql
    ports:
      - "8000:8000"
    volumes:
      - .:/new_site
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: re-play
      POSTGRES_DB: sql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
