version: '3'

services:
  web:
    build: .
    environment:
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - user_photos:/app/docstar_site/docstar/user_photos/user_photos
      - .:/new_site
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  user_photos: