version: '3.6'

services:
  web:
    build: .
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - LOCAL_PYTEST=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DEBUG=${DEBUG}
      - ENVIRONMENT_TYPE=docker
    ports:
      - "8000:8000"
    volumes:
      - user_photos:/app/docstar_site/docstar/user_photos/user_photos
      - .:/new_site
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./${DUMP_DIR}:/tmp/dumps
      - ./${DUMP_DIR}/${DB_DUMP}:/docker-entrypoint-initdb.d/02dump.sql

volumes:
  pg_data:
  user_photos: