version: '3'

services:
  web:
    build: .
    environment:
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/new_site
    depends_on:
      - postgres
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
