version: '3'

services:
  web:
    build: .
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: re-play
      DB_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/new_site
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: re-play
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
