# Generated by Django 4.1.5 on 2023-10-14 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя Блогера')),
                ('username', models.CharField(max_length=255, verbose_name='Username Telegram блогера')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram_id')),
                ('sb_id', models.BigIntegerField(unique=True, verbose_name='Salebot_id')),
                ('discount', models.IntegerField(blank=True, default=10, verbose_name='Процент скидки')),
                ('registration_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('pay_date', models.IntegerField(blank=True, default=1, verbose_name='Дата расчетов')),
            ],
            options={
                'verbose_name': 'Блогер',
                'verbose_name_plural': 'Блогеры',
            },
        ),
        migrations.CreateModel(
            name='UTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UTM-метка',
                'verbose_name_plural': 'UTM-метки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username Telegram клиента')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram_id')),
                ('sb_id', models.BigIntegerField(unique=True, verbose_name='Salebot_id')),
                ('gk_id', models.BigIntegerField(unique=True, verbose_name='GetCourse_id')),
                ('registration_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('blogger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.blogger', verbose_name='Блогер')),
                ('utm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.utm', verbose_name='UTM-метка')),
            ],
            options={
                'verbose_name': 'Клиент купивший VPN',
                'verbose_name_plural': 'Клиенты купившие VPN',
            },
        ),
        migrations.AddField(
            model_name='blogger',
            name='utm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.utm', verbose_name='UTM-метка'),
        ),
    ]
