# Generated by Django 4.1.5 on 2024-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LtvClubReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Созданный'), ('Pending', 'В процессе'), ('Error', 'Ошибка'), ('Completed', 'Завершен')], default='Created', max_length=40, verbose_name='Статус создания отчета')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='ltv_club_reports', verbose_name='Файл с отчетами')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания отчета')),
                ('export_id', models.CharField(max_length=40, unique=True, verbose_name='Export_id')),
                ('export_time', models.DateTimeField(auto_now=True, verbose_name='Время экспорта')),
            ],
            options={
                'verbose_name': 'Отчет по LTV клуба',
                'verbose_name_plural': 'Отчеты по LTV клуба',
            },
        ),
    ]
